# Generated by Django 4.1.2 on 2022-11-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_imageurls',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
